# Use root/example as user/password credentials
version: '3.8'

services:

  
  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - local

  agendaback:
    container_name: agendaback
    image: agendaback
    restart: always
    build:
      context: ./AgendaBack
      dockerfile: Dockerfile

    environment:
      - PG_HOST=mysql
    networks:
      - local
    ports:
      - 3333:3333
    expose:
      - 3333
    env_file:
      - ./AgendaBack/.env
    volumes:
      - ./AgendaBack:/home/node/app/
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

  agendafront:
    container_name: agendafront
    image: agendafront
    build: 
      context: ./AgendaFront
      dockerfile: Dockerfile
    ports:
      - 8081:80
    environment:
      - API_HOST=adonis
      - API_PORT=3333
    networks:
      - local

  
networks:
  local:
    name: localdocker
    